rm -f *.pyd
copy ..\\..\\..\\c\\ccpnmr\\analysis\\ContourFile.pyd ContourFile.pyd
copy ..\\..\\..\\c\\ccpnmr\\analysis\\ContourLevels.pyd ContourLevels.pyd
copy ..\\..\\..\\c\\ccpnmr\\analysis\\ContourStyle.pyd ContourStyle.pyd
copy ..\\..\\..\\c\\ccpnmr\\analysis\\PeakCluster.pyd PeakCluster.pyd
copy ..\\..\\..\\c\\ccpnmr\\analysis\\PeakList.pyd PeakList.pyd
copy ..\\..\\..\\c\\ccpnmr\\analysis\\SliceFile.pyd SliceFile.pyd
copy ..\\..\\..\\c\\ccpnmr\\analysis\\WinPeakList.pyd WinPeakList.pyd
copy ..\\..\\..\\c\\ccpnmr\\clouds\\AtomCoord.pyd .
copy ..\\..\\..\\c\\ccpnmr\\clouds\\AtomCoordList.pyd .
copy ..\\..\\..\\c\\ccpnmr\\clouds\\DistConstraint.pyd .
copy ..\\..\\..\\c\\ccpnmr\\clouds\\DistConstraintList.pyd .
copy ..\\..\\..\\c\\ccpnmr\\clouds\\DistForce.pyd .
copy ..\\..\\..\\c\\ccpnmr\\clouds\\Dynamics.pyd .
copy ..\\..\\..\\c\\ccpnmr\\clouds\\Midge.pyd .
copy ..\\..\\..\\c\\ccpnmr\\clouds\\Bacus.pyd .
