"""
#######################################################################

CCPN Data Model version 2.1.2

Autogenerated by PyXmlMapWrite revision 1.29 on Mon Mar  2 17:24:10 2015
  from data model element ccpnmr.AnalysisLayout revision ?

#######################################################################
======================COPYRIGHT/LICENSE START==========================

AnalysisLayout.py: python XML-I/O-mapping for CCPN data model, MetaPackage ccpnmr.AnalysisLayout

Copyright (C) 2007  (CCPN Project)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
 
A copy of this license can be found in ../../../license/LGPL.license
 
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.
 
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- CCPN website (http://www.ccpn.ac.uk/)

- email: ccpn@bioc.cam.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
Rasmus H. Fogh, Wayne Boucher, Wim F. Vranken, Anne
Pajon, Tim J. Stevens, T.N. Bhat, John Westbrook, John M.C. Ionides and
Ernest D. Laue (2005). A framework for scientific data modeling and automated
software development. Bioinformatics 21, 1678-1684.


This file was generated with the Memops software generation framework,
and contains original contributions embedded in the framework

===========================REFERENCE END===============================
"""
from memops.general.Constants import baseDataTypeModule as basicDataTypes
# 
#  Current package api
import ccpnmr.api.AnalysisLayout

def makeMapping(globalMap):
  """
  generates XML I/O mapping for package ANAY, adding it to globalMap
  """
  
  from memops.xml.Implementation import bool2str, str2bool

  # Set up top level dictionaries
  loadMaps = globalMap.get('loadMaps')
  mapsByGuid = globalMap.get('mapsByGuid')

  abstractTypes = globalMap.get('ANAY').get('abstractTypes')
  exolinks = globalMap.get('ANAY').get('exolinks')

  # DataType LayoutArea
  currentMap = {}
  abstractTypes['LayoutArea'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-08-16-17:30:27_00002'] = currentMap
  loadMaps['ANAY.LayoutArea'] = currentMap
  currentMap['tag'] = 'ANAY.LayoutArea'
  currentMap['type'] = 'simple'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-08-16-17:30:27_00002'
  currentMap['toStr'] = 'text'
  currentMap['cnvrt'] = 'text'

  # DataType SpectrumSharing
  currentMap = {}
  abstractTypes['SpectrumSharing'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-08-16-17:30:27_00001'] = currentMap
  loadMaps['ANAY.SpectrumSharing'] = currentMap
  currentMap['tag'] = 'ANAY.SpectrumSharing'
  currentMap['type'] = 'simple'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-08-16-17:30:27_00001'
  currentMap['toStr'] = 'text'
  currentMap['cnvrt'] = 'text'

  # Class AbstractMarking
  currentMap = {}
  abstractTypes['AbstractMarking'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-10:49:23_00004'] = currentMap
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-10:49:23_00004'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.AbstractMarking
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AbstractMarking.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AbstractMarking.axisCode
  currentMap = {}
  contentMap['axisCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00007'] = currentMap
  loadMaps['ANAY.AbstractMarking.axisCode'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractMarking.axisCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00007'
  currentMap['name'] = 'axisCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute AbstractMarking.position
  currentMap = {}
  contentMap['position'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00005'] = currentMap
  loadMaps['ANAY.AbstractMarking.position'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractMarking.position'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00005'
  currentMap['name'] = 'position'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute AbstractMarking.unit
  currentMap = {}
  contentMap['unit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00006'] = currentMap
  loadMaps['ANAY.AbstractMarking.unit'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractMarking.unit'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00006'
  currentMap['name'] = 'unit'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Role AbstractMarking.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role AbstractMarking.axisType
  currentMap = {}
  contentMap['axisType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00003'] = currentMap
  loadMaps['ANAY.AbstractMarking.axisType'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractMarking.axisType'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00003'
  currentMap['name'] = 'axisType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('ANAW').get('exolinks')

  # Role AbstractMarking.axisUnit
  currentMap = {}
  contentMap['axisUnit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00004'] = currentMap
  loadMaps['ANAY.AbstractMarking.axisUnit'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractMarking.axisUnit'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00004'
  currentMap['name'] = 'axisUnit'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('ANAW').get('exolinks')
  # End of AbstractMarking

  currentMap = abstractTypes.get('AbstractMarking')
  aList = ['axisCode', 'position', 'unit']
  currentMap['headerAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class AbstractPanel
  currentMap = {}
  abstractTypes['AbstractPanel'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00015'] = currentMap
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00015'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'panels'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.AbstractPanel
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AbstractPanel.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AbstractPanel.gridCell
  currentMap = {}
  contentMap['gridCell'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00020'] = currentMap
  loadMaps['ANAY.AbstractPanel.gridCell'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.gridCell'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00020'
  currentMap['name'] = 'gridCell'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [0, 0]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute AbstractPanel.gridSpan
  currentMap = {}
  contentMap['gridSpan'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00021'] = currentMap
  loadMaps['ANAY.AbstractPanel.gridSpan'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.gridSpan'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00021'
  currentMap['name'] = 'gridSpan'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [1, 1]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00001')

  # Attribute AbstractPanel.isCollapsed
  currentMap = {}
  contentMap['isCollapsed'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00001'] = currentMap
  loadMaps['ANAY.AbstractPanel.isCollapsed'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.isCollapsed'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00001'
  currentMap['name'] = 'isCollapsed'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute AbstractPanel.layoutArea
  currentMap = {}
  contentMap['layoutArea'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00001'] = currentMap
  loadMaps['ANAY.AbstractPanel.layoutArea'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.layoutArea'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00001'
  currentMap['name'] = 'layoutArea'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 'middle'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-08-16-17:30:27_00002')

  # Attribute AbstractPanel.moduleCode
  currentMap = {}
  contentMap['moduleCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00019'] = currentMap
  loadMaps['ANAY.AbstractPanel.moduleCode'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.moduleCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00019'
  currentMap['name'] = 'moduleCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute AbstractPanel.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-05-03-14:05:48_00001'] = currentMap
  loadMaps['ANAY.AbstractPanel.name'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-05-03-14:05:48_00001'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute AbstractPanel.rank
  currentMap = {}
  contentMap['rank'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-04-18-15:31:21_00001'] = currentMap
  loadMaps['ANAY.AbstractPanel.rank'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.rank'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-04-18-15:31:21_00001'
  currentMap['name'] = 'rank'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00001')

  # Attribute AbstractPanel.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00018'] = currentMap
  loadMaps['ANAY.AbstractPanel.serial'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00018'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role AbstractPanel.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role AbstractPanel.actionLinks
  currentMap = {}
  contentMap['actionLinks'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00013'] = currentMap
  loadMaps['ANAY.AbstractPanel.actionLinks'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.actionLinks'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00013'
  currentMap['name'] = 'actionLinks'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role AbstractPanel.listenLinks
  currentMap = {}
  contentMap['listenLinks'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00015'] = currentMap
  loadMaps['ANAY.AbstractPanel.listenLinks'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.listenLinks'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00015'
  currentMap['name'] = 'listenLinks'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False

  # Role AbstractPanel.module
  currentMap = {}
  contentMap['module'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00005'] = currentMap
  loadMaps['ANAY.AbstractPanel.module'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.module'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00005'
  currentMap['name'] = 'module'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('ANAW').get('exolinks')

  # Role AbstractPanel.parameters
  currentMap = {}
  contentMap['parameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00017'] = currentMap
  loadMaps['ANAY.AbstractPanel.parameters'] = currentMap
  currentMap['tag'] = 'ANAY.AbstractPanel.parameters'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00017'
  currentMap['name'] = 'parameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')
  # End of AbstractPanel

  currentMap = abstractTypes.get('AbstractPanel')
  aList = ['isCollapsed', 'layoutArea', 'moduleCode', 'rank', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['gridCell', 'gridSpan', 'name', 'listenLinks']
  currentMap['simpleAttrs'] = aList
  aList = ['parameters', 'actionLinks', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['actionLinks', 'parameters']
  currentMap['children'] = aList

  # Class ActionLink
  currentMap = {}
  abstractTypes['ActionLink'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00016'] = currentMap
  loadMaps['ANAY.ActionLink'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLink'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00016'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'actionLinks'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.ActionLink
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ActionLink.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ActionLink.role
  currentMap = {}
  contentMap['role'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00007'] = currentMap
  loadMaps['ANAY.ActionLink.role'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLink.role'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00007'
  currentMap['name'] = 'role'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute ActionLink.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00006'] = currentMap
  loadMaps['ANAY.ActionLink.serial'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLink.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00006'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role ActionLink.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role ActionLink.parameters
  currentMap = {}
  contentMap['parameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00005'] = currentMap
  loadMaps['ANAY.ActionLink.parameters'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLink.parameters'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00005'
  currentMap['name'] = 'parameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role ActionLink.target
  currentMap = {}
  contentMap['target'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00014'] = currentMap
  loadMaps['ANAY.ActionLink.target'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLink.target'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00014'
  currentMap['name'] = 'target'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['copyOverride'] = True
  # End of ActionLink

  currentMap = abstractTypes.get('ActionLink')
  aList = ['role', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['target']
  currentMap['optLinks'] = aList
  aList = ['parameters', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['parameters']
  currentMap['children'] = aList

  # Class ActionLinkParameter
  currentMap = {}
  abstractTypes['ActionLinkParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00028'] = currentMap
  loadMaps['ANAY.ActionLinkParameter'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLinkParameter'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00028'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'parameters'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.ActionLinkParameter
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ActionLinkParameter.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ActionLinkParameter.booleanValue
  contentMap['booleanValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00008')

  # Attribute ActionLinkParameter.description
  currentMap = {}
  contentMap['description'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00009'] = currentMap
  loadMaps['ANAY.ActionLinkParameter.description'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLinkParameter.description'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00009'
  currentMap['name'] = 'description'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ActionLinkParameter.floatValue
  contentMap['floatValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00007')

  # Attribute ActionLinkParameter.intValue
  contentMap['intValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00006')

  # Attribute ActionLinkParameter.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00008'] = currentMap
  loadMaps['ANAY.ActionLinkParameter.name'] = currentMap
  currentMap['tag'] = 'ANAY.ActionLinkParameter.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00008'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute ActionLinkParameter.textValue
  contentMap['textValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00005')

  # Role ActionLinkParameter.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of ActionLinkParameter

  currentMap = abstractTypes.get('ActionLinkParameter')
  aList = ['booleanValue', 'floatValue', 'intValue', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['description', 'textValue']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class AxisGroup
  currentMap = {}
  abstractTypes['AxisGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00020'] = currentMap
  loadMaps['ANAY.AxisGroup'] = currentMap
  currentMap['tag'] = 'ANAY.AxisGroup'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00020'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'axisGroups'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.AxisGroup
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AxisGroup.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AxisGroup.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00012'] = currentMap
  loadMaps['ANAY.AxisGroup.serial'] = currentMap
  currentMap['tag'] = 'ANAY.AxisGroup.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00012'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role AxisGroup.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role AxisGroup.panelAxes
  currentMap = {}
  contentMap['panelAxes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00011'] = currentMap
  loadMaps['ANAY.AxisGroup.panelAxes'] = currentMap
  currentMap['tag'] = 'ANAY.AxisGroup.panelAxes'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00011'
  currentMap['name'] = 'panelAxes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of AxisGroup

  currentMap = abstractTypes.get('AxisGroup')
  aList = ['serial']
  currentMap['headerAttrs'] = aList
  aList = ['panelAxes']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class Layout
  currentMap = {}
  abstractTypes['Layout'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00011'] = currentMap
  loadMaps['ANAY.Layout'] = currentMap
  currentMap['tag'] = 'ANAY.Layout'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00011'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'layouts'
  currentMap['isTop'] = True
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.Layout
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Layout.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Layout.createdBy
  contentMap['createdBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00002__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute Layout.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00004'] = currentMap
  loadMaps['ANAY.Layout.details'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00004'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute Layout.guid
  contentMap['guid'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:26_00002')

  # Attribute Layout.helpUrl
  currentMap = {}
  contentMap['helpUrl'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00006'] = currentMap
  loadMaps['ANAY.Layout.helpUrl'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.helpUrl'
  currentMap['type'] = 'dobj'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00006'
  currentMap['name'] = 'helpUrl'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('IMPL').get('abstractTypes')

  # Attribute Layout.isActive
  currentMap = {}
  contentMap['isActive'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00007'] = currentMap
  loadMaps['ANAY.Layout.isActive'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.isActive'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00007'
  currentMap['name'] = 'isActive'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Layout.isDefault
  currentMap = {}
  contentMap['isDefault'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00008'] = currentMap
  loadMaps['ANAY.Layout.isDefault'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.isDefault'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00008'
  currentMap['name'] = 'isDefault'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Layout.isModifiable
  contentMap['isModifiable'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-17-14:16:26_00010__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute Layout.keywords
  currentMap = {}
  contentMap['keywords'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-05-14-13:21:09_00001'] = currentMap
  loadMaps['ANAY.Layout.keywords'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.keywords'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-05-14-13:21:09_00001'
  currentMap['name'] = 'keywords'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Layout.lastUnlockedBy
  contentMap['lastUnlockedBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00003__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute Layout.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00003'] = currentMap
  loadMaps['ANAY.Layout.name'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00003'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Layout.rank
  currentMap = {}
  contentMap['rank'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-09-10-14:34:35_00001'] = currentMap
  loadMaps['ANAY.Layout.rank'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.rank'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-09-10-14:34:35_00001'
  currentMap['name'] = 'rank'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00001')

  # Attribute Layout.shortcut
  currentMap = {}
  contentMap['shortcut'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00005'] = currentMap
  loadMaps['ANAY.Layout.shortcut'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.shortcut'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00005'
  currentMap['name'] = 'shortcut'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Layout.showWindowDepth
  currentMap = {}
  contentMap['showWindowDepth'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00011'] = currentMap
  loadMaps['ANAY.Layout.showWindowDepth'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.showWindowDepth'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00011'
  currentMap['name'] = 'showWindowDepth'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Layout.showWindowLabels
  currentMap = {}
  contentMap['showWindowLabels'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00009'] = currentMap
  loadMaps['ANAY.Layout.showWindowLabels'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.showWindowLabels'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00009'
  currentMap['name'] = 'showWindowLabels'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Layout.showWindowMidpoint
  currentMap = {}
  contentMap['showWindowMidpoint'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00010'] = currentMap
  loadMaps['ANAY.Layout.showWindowMidpoint'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.showWindowMidpoint'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00010'
  currentMap['name'] = 'showWindowMidpoint'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Role Layout.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role Layout.axisGroups
  currentMap = {}
  contentMap['axisGroups'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00020'] = currentMap
  loadMaps['ANAY.Layout.axisGroups'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.axisGroups'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00020'
  currentMap['name'] = 'axisGroups'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role Layout.marks
  currentMap = {}
  contentMap['marks'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00014'] = currentMap
  loadMaps['ANAY.Layout.marks'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.marks'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00014'
  currentMap['name'] = 'marks'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role Layout.panels
  currentMap = {}
  contentMap['panels'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00018'] = currentMap
  loadMaps['ANAY.Layout.panels'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.panels'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00018'
  currentMap['name'] = 'panels'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role Layout.parameters
  currentMap = {}
  contentMap['parameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00002'] = currentMap
  loadMaps['ANAY.Layout.parameters'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.parameters'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00002'
  currentMap['name'] = 'parameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role Layout.rulers
  currentMap = {}
  contentMap['rulers'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00016'] = currentMap
  loadMaps['ANAY.Layout.rulers'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.rulers'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00016'
  currentMap['name'] = 'rulers'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role Layout.windowPanelGroups
  currentMap = {}
  contentMap['windowPanelGroups'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00022'] = currentMap
  loadMaps['ANAY.Layout.windowPanelGroups'] = currentMap
  currentMap['tag'] = 'ANAY.Layout.windowPanelGroups'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00022'
  currentMap['name'] = 'windowPanelGroups'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')
  # End of Layout

  currentMap = abstractTypes.get('Layout')
  aList = ['createdBy', 'guid', 'isActive', 'isDefault', 'isModifiable', 'lastUnlockedBy', 'rank', 'shortcut', 'showWindowDepth', 'showWindowLabels', 'showWindowMidpoint']
  currentMap['headerAttrs'] = aList
  aList = ['details', 'keywords', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['windowPanelGroups', 'rulers', 'parameters', 'panels', 'marks', 'axisGroups', 'access', 'helpUrl', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['axisGroups', 'marks', 'panels', 'parameters', 'rulers', 'windowPanelGroups']
  currentMap['children'] = aList

  # Class LayoutParameter
  currentMap = {}
  abstractTypes['LayoutParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00030'] = currentMap
  loadMaps['ANAY.LayoutParameter'] = currentMap
  currentMap['tag'] = 'ANAY.LayoutParameter'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00030'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'parameters'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.LayoutParameter
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute LayoutParameter.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute LayoutParameter.booleanValue
  contentMap['booleanValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00008')

  # Attribute LayoutParameter.description
  currentMap = {}
  contentMap['description'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00013'] = currentMap
  loadMaps['ANAY.LayoutParameter.description'] = currentMap
  currentMap['tag'] = 'ANAY.LayoutParameter.description'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00013'
  currentMap['name'] = 'description'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute LayoutParameter.floatValue
  contentMap['floatValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00007')

  # Attribute LayoutParameter.intValue
  contentMap['intValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00006')

  # Attribute LayoutParameter.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00012'] = currentMap
  loadMaps['ANAY.LayoutParameter.name'] = currentMap
  currentMap['tag'] = 'ANAY.LayoutParameter.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00012'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute LayoutParameter.textValue
  contentMap['textValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00005')

  # Role LayoutParameter.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of LayoutParameter

  currentMap = abstractTypes.get('LayoutParameter')
  aList = ['booleanValue', 'floatValue', 'intValue', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['description', 'textValue']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class Mark
  currentMap = {}
  abstractTypes['Mark'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00012'] = currentMap
  loadMaps['ANAY.Mark'] = currentMap
  currentMap['tag'] = 'ANAY.Mark'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00012'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'marks'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.Mark
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Mark.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Mark.color
  currentMap = {}
  contentMap['color'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00017'] = currentMap
  loadMaps['ANAY.Mark.color'] = currentMap
  currentMap['tag'] = 'ANAY.Mark.color'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00017'
  currentMap['name'] = 'color'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['default'] = '#808080FF'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-12-02-09:49:50_00003')

  # Attribute Mark.dashLength
  currentMap = {}
  contentMap['dashLength'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00018'] = currentMap
  loadMaps['ANAY.Mark.dashLength'] = currentMap
  currentMap['tag'] = 'ANAY.Mark.dashLength'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00018'
  currentMap['name'] = 'dashLength'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00001')

  # Attribute Mark.gapLength
  currentMap = {}
  contentMap['gapLength'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00019'] = currentMap
  loadMaps['ANAY.Mark.gapLength'] = currentMap
  currentMap['tag'] = 'ANAY.Mark.gapLength'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00019'
  currentMap['name'] = 'gapLength'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute Mark.lineWidth
  currentMap = {}
  contentMap['lineWidth'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00020'] = currentMap
  loadMaps['ANAY.Mark.lineWidth'] = currentMap
  currentMap['tag'] = 'ANAY.Mark.lineWidth'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00020'
  currentMap['name'] = 'lineWidth'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1.0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00007')

  # Attribute Mark.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00016'] = currentMap
  loadMaps['ANAY.Mark.serial'] = currentMap
  currentMap['tag'] = 'ANAY.Mark.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00016'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role Mark.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role Mark.markDims
  currentMap = {}
  contentMap['markDims'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00015'] = currentMap
  loadMaps['ANAY.Mark.markDims'] = currentMap
  currentMap['tag'] = 'ANAY.Mark.markDims'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00015'
  currentMap['name'] = 'markDims'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')
  # End of Mark

  currentMap = abstractTypes.get('Mark')
  aList = ['dashLength', 'gapLength', 'lineWidth', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['color']
  currentMap['simpleAttrs'] = aList
  aList = ['markDims', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['markDims']
  currentMap['children'] = aList

  # Class PanelAxis
  currentMap = {}
  abstractTypes['PanelAxis'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00019'] = currentMap
  loadMaps['ANAY.PanelAxis'] = currentMap
  currentMap['tag'] = 'ANAY.PanelAxis'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00019'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'panelAxes'
  currentMap['objkey'] = 'label'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.PanelAxis
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute PanelAxis.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute PanelAxis.label
  currentMap = {}
  contentMap['label'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00025'] = currentMap
  loadMaps['ANAY.PanelAxis.label'] = currentMap
  currentMap['tag'] = 'ANAY.PanelAxis.label'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00025'
  currentMap['name'] = 'label'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute PanelAxis.region
  currentMap = {}
  contentMap['region'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00026'] = currentMap
  loadMaps['ANAY.PanelAxis.region'] = currentMap
  currentMap['tag'] = 'ANAY.PanelAxis.region'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00026'
  currentMap['name'] = 'region'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [0.0, 1.0]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute PanelAxis.showScale
  currentMap = {}
  contentMap['showScale'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00027'] = currentMap
  loadMaps['ANAY.PanelAxis.showScale'] = currentMap
  currentMap['tag'] = 'ANAY.PanelAxis.showScale'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00027'
  currentMap['name'] = 'showScale'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Role PanelAxis.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role PanelAxis.axisGroup
  currentMap = {}
  contentMap['axisGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00010'] = currentMap
  loadMaps['ANAY.PanelAxis.axisGroup'] = currentMap
  currentMap['tag'] = 'ANAY.PanelAxis.axisGroup'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00010'
  currentMap['name'] = 'axisGroup'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True
  # End of PanelAxis

  currentMap = abstractTypes.get('PanelAxis')
  aList = ['label', 'showScale']
  currentMap['headerAttrs'] = aList
  aList = ['region']
  currentMap['simpleAttrs'] = aList
  aList = ['axisGroup']
  currentMap['optLinks'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class PanelGroupParameter
  currentMap = {}
  abstractTypes['PanelGroupParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00031'] = currentMap
  loadMaps['ANAY.PanelGroupParameter'] = currentMap
  currentMap['tag'] = 'ANAY.PanelGroupParameter'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00031'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'parameters'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.PanelGroupParameter
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute PanelGroupParameter.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute PanelGroupParameter.booleanValue
  contentMap['booleanValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00008')

  # Attribute PanelGroupParameter.description
  currentMap = {}
  contentMap['description'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00030'] = currentMap
  loadMaps['ANAY.PanelGroupParameter.description'] = currentMap
  currentMap['tag'] = 'ANAY.PanelGroupParameter.description'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00030'
  currentMap['name'] = 'description'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute PanelGroupParameter.floatValue
  contentMap['floatValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00007')

  # Attribute PanelGroupParameter.intValue
  contentMap['intValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00006')

  # Attribute PanelGroupParameter.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00029'] = currentMap
  loadMaps['ANAY.PanelGroupParameter.name'] = currentMap
  currentMap['tag'] = 'ANAY.PanelGroupParameter.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00029'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute PanelGroupParameter.textValue
  contentMap['textValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00005')

  # Role PanelGroupParameter.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of PanelGroupParameter

  currentMap = abstractTypes.get('PanelGroupParameter')
  aList = ['booleanValue', 'floatValue', 'intValue', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['description', 'textValue']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class PanelParameter
  currentMap = {}
  abstractTypes['PanelParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00029'] = currentMap
  loadMaps['ANAY.PanelParameter'] = currentMap
  currentMap['tag'] = 'ANAY.PanelParameter'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00029'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'parameters'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.PanelParameter
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute PanelParameter.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute PanelParameter.booleanValue
  contentMap['booleanValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00008')

  # Attribute PanelParameter.description
  currentMap = {}
  contentMap['description'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00002'] = currentMap
  loadMaps['ANAY.PanelParameter.description'] = currentMap
  currentMap['tag'] = 'ANAY.PanelParameter.description'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00002'
  currentMap['name'] = 'description'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute PanelParameter.floatValue
  contentMap['floatValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00007')

  # Attribute PanelParameter.intValue
  contentMap['intValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00006')

  # Attribute PanelParameter.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00001'] = currentMap
  loadMaps['ANAY.PanelParameter.name'] = currentMap
  currentMap['tag'] = 'ANAY.PanelParameter.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00001'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute PanelParameter.textValue
  contentMap['textValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00005')

  # Role PanelParameter.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of PanelParameter

  currentMap = abstractTypes.get('PanelParameter')
  aList = ['booleanValue', 'floatValue', 'intValue', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['description', 'textValue']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class WindowPanelGroup
  currentMap = {}
  abstractTypes['WindowPanelGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00021'] = currentMap
  loadMaps['ANAY.WindowPanelGroup'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00021'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'windowPanelGroups'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.WindowPanelGroup
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute WindowPanelGroup.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute WindowPanelGroup.gridCell
  currentMap = {}
  contentMap['gridCell'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-04-13-13:34:58_00002'] = currentMap
  loadMaps['ANAY.WindowPanelGroup.gridCell'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup.gridCell'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-04-13-13:34:58_00002'
  currentMap['name'] = 'gridCell'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [0, 0]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute WindowPanelGroup.gridSpan
  currentMap = {}
  contentMap['gridSpan'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-04-13-13:40:40_00001'] = currentMap
  loadMaps['ANAY.WindowPanelGroup.gridSpan'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup.gridSpan'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-04-13-13:40:40_00001'
  currentMap['name'] = 'gridSpan'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [1, 1]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00001')

  # Attribute WindowPanelGroup.isGridGroup
  currentMap = {}
  contentMap['isGridGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-04-13-13:34:58_00001'] = currentMap
  loadMaps['ANAY.WindowPanelGroup.isGridGroup'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup.isGridGroup'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-04-13-13:34:58_00001'
  currentMap['name'] = 'isGridGroup'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanelGroup.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00003'] = currentMap
  loadMaps['ANAY.WindowPanelGroup.serial'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00003'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute WindowPanelGroup.spectrumSharing
  currentMap = {}
  contentMap['spectrumSharing'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00002'] = currentMap
  loadMaps['ANAY.WindowPanelGroup.spectrumSharing'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup.spectrumSharing'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00002'
  currentMap['name'] = 'spectrumSharing'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-08-16-17:30:27_00001')

  # Role WindowPanelGroup.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role WindowPanelGroup.parameters
  currentMap = {}
  contentMap['parameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00002'] = currentMap
  loadMaps['ANAY.WindowPanelGroup.parameters'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup.parameters'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00002'
  currentMap['name'] = 'parameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role WindowPanelGroup.windowPanels
  currentMap = {}
  contentMap['windowPanels'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00003'] = currentMap
  loadMaps['ANAY.WindowPanelGroup.windowPanels'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelGroup.windowPanels'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00003'
  currentMap['name'] = 'windowPanels'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of WindowPanelGroup

  currentMap = abstractTypes.get('WindowPanelGroup')
  aList = ['isGridGroup', 'serial', 'spectrumSharing']
  currentMap['headerAttrs'] = aList
  aList = ['gridCell', 'gridSpan', 'windowPanels']
  currentMap['simpleAttrs'] = aList
  aList = ['parameters', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['parameters']
  currentMap['children'] = aList

  # Class MarkDim
  currentMap = {}
  abstractTypes['MarkDim'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00013'] = currentMap
  loadMaps['ANAY.MarkDim'] = currentMap
  currentMap['tag'] = 'ANAY.MarkDim'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00013'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'markDims'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.MarkDim
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute MarkDim.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute MarkDim.axisCode
  contentMap['axisCode'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00007')

  # Attribute MarkDim.position
  contentMap['position'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00005')

  # Attribute MarkDim.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00021'] = currentMap
  loadMaps['ANAY.MarkDim.serial'] = currentMap
  currentMap['tag'] = 'ANAY.MarkDim.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:43_00021'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute MarkDim.unit
  contentMap['unit'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00006')

  # Role MarkDim.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role MarkDim.axisType
  contentMap['axisType'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00003')

  # Role MarkDim.axisUnit
  contentMap['axisUnit'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00004')
  # End of MarkDim

  currentMap = abstractTypes.get('MarkDim')
  aList = ['axisCode', 'position', 'serial', 'unit']
  currentMap['headerAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class Ruler
  currentMap = {}
  abstractTypes['Ruler'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00014'] = currentMap
  loadMaps['ANAY.Ruler'] = currentMap
  currentMap['tag'] = 'ANAY.Ruler'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00014'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'rulers'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.Ruler
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Ruler.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Ruler.axisCode
  contentMap['axisCode'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00007')

  # Attribute Ruler.color
  currentMap = {}
  contentMap['color'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00006'] = currentMap
  loadMaps['ANAY.Ruler.color'] = currentMap
  currentMap['tag'] = 'ANAY.Ruler.color'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00006'
  currentMap['name'] = 'color'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['default'] = '#808080FF'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-12-02-09:49:50_00003')

  # Attribute Ruler.dashLength
  currentMap = {}
  contentMap['dashLength'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00007'] = currentMap
  loadMaps['ANAY.Ruler.dashLength'] = currentMap
  currentMap['tag'] = 'ANAY.Ruler.dashLength'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00007'
  currentMap['name'] = 'dashLength'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00001')

  # Attribute Ruler.lineWidth
  currentMap = {}
  contentMap['lineWidth'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00004'] = currentMap
  loadMaps['ANAY.Ruler.lineWidth'] = currentMap
  currentMap['tag'] = 'ANAY.Ruler.lineWidth'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00004'
  currentMap['name'] = 'lineWidth'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1.0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00007')

  # Attribute Ruler.position
  contentMap['position'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00005')

  # Attribute Ruler.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00003'] = currentMap
  loadMaps['ANAY.Ruler.serial'] = currentMap
  currentMap['tag'] = 'ANAY.Ruler.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00003'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute Ruler.unit
  contentMap['unit'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00006')

  # Role Ruler.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role Ruler.axisType
  contentMap['axisType'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00003')

  # Role Ruler.axisUnit
  contentMap['axisUnit'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00004')
  # End of Ruler

  currentMap = abstractTypes.get('Ruler')
  aList = ['axisCode', 'dashLength', 'lineWidth', 'position', 'serial', 'unit']
  currentMap['headerAttrs'] = aList
  aList = ['color']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class ModulePanel
  currentMap = {}
  abstractTypes['ModulePanel'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00018'] = currentMap
  loadMaps['ANAY.ModulePanel'] = currentMap
  currentMap['tag'] = 'ANAY.ModulePanel'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00018'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'panels'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.ModulePanel
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ModulePanel.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ModulePanel.gridCell
  contentMap['gridCell'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00020')

  # Attribute ModulePanel.gridSpan
  contentMap['gridSpan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00021')

  # Attribute ModulePanel.isCollapsed
  contentMap['isCollapsed'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00001')

  # Attribute ModulePanel.layoutArea
  contentMap['layoutArea'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00001')

  # Attribute ModulePanel.moduleCode
  contentMap['moduleCode'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00019')

  # Attribute ModulePanel.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-05-03-14:05:48_00001')

  # Attribute ModulePanel.rank
  contentMap['rank'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-04-18-15:31:21_00001')

  # Attribute ModulePanel.serial
  contentMap['serial'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00018')

  # Role ModulePanel.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role ModulePanel.actionLinks
  contentMap['actionLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00013')

  # Role ModulePanel.listenLinks
  contentMap['listenLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00015')

  # Role ModulePanel.module
  contentMap['module'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00005')

  # Role ModulePanel.parameters
  contentMap['parameters'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00017')
  # End of ModulePanel

  currentMap = abstractTypes.get('ModulePanel')
  aList = ['isCollapsed', 'layoutArea', 'moduleCode', 'rank', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['gridCell', 'gridSpan', 'name', 'listenLinks']
  currentMap['simpleAttrs'] = aList
  aList = ['parameters', 'actionLinks', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['actionLinks', 'parameters']
  currentMap['children'] = aList

  # Class WindowPanel
  currentMap = {}
  abstractTypes['WindowPanel'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00017'] = currentMap
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00017'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'panels'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.WindowPanel
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute WindowPanel.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute WindowPanel.gridCell
  contentMap['gridCell'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00020')

  # Attribute WindowPanel.gridSpan
  contentMap['gridSpan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00021')

  # Attribute WindowPanel.isCollapsed
  contentMap['isCollapsed'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00001')

  # Attribute WindowPanel.layoutArea
  contentMap['layoutArea'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00001')

  # Attribute WindowPanel.moduleCode
  contentMap['moduleCode'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00019')

  # Attribute WindowPanel.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-05-03-14:05:48_00001')

  # Attribute WindowPanel.rank
  contentMap['rank'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-04-18-15:31:21_00001')

  # Attribute WindowPanel.serial
  contentMap['serial'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00018')

  # Attribute WindowPanel.showCouplings
  currentMap = {}
  contentMap['showCouplings'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00016'] = currentMap
  loadMaps['ANAY.WindowPanel.showCouplings'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel.showCouplings'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00016'
  currentMap['name'] = 'showCouplings'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel.showMultiplets
  currentMap = {}
  contentMap['showMultiplets'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00015'] = currentMap
  loadMaps['ANAY.WindowPanel.showMultiplets'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel.showMultiplets'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00015'
  currentMap['name'] = 'showMultiplets'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel.showPosition
  currentMap = {}
  contentMap['showPosition'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00017'] = currentMap
  loadMaps['ANAY.WindowPanel.showPosition'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel.showPosition'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00017'
  currentMap['name'] = 'showPosition'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel.showStructure
  currentMap = {}
  contentMap['showStructure'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00014'] = currentMap
  loadMaps['ANAY.WindowPanel.showStructure'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel.showStructure'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00014'
  currentMap['name'] = 'showStructure'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel.useMultiplePeakLists
  currentMap = {}
  contentMap['useMultiplePeakLists'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00013'] = currentMap
  loadMaps['ANAY.WindowPanel.useMultiplePeakLists'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel.useMultiplePeakLists'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00013'
  currentMap['name'] = 'useMultiplePeakLists'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Role WindowPanel.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role WindowPanel.actionLinks
  contentMap['actionLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00013')

  # Role WindowPanel.listenLinks
  contentMap['listenLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00015')

  # Role WindowPanel.module
  contentMap['module'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00005')

  # Role WindowPanel.panelAxes
  currentMap = {}
  contentMap['panelAxes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00009'] = currentMap
  loadMaps['ANAY.WindowPanel.panelAxes'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel.panelAxes'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00009'
  currentMap['name'] = 'panelAxes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAY').get('abstractTypes')

  # Role WindowPanel.parameters
  contentMap['parameters'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00017')

  # Role WindowPanel.windowPanelGroup
  currentMap = {}
  contentMap['windowPanelGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00002'] = currentMap
  loadMaps['ANAY.WindowPanel.windowPanelGroup'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel.windowPanelGroup'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00002'
  currentMap['name'] = 'windowPanelGroup'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True
  # End of WindowPanel

  currentMap = abstractTypes.get('WindowPanel')
  aList = ['isCollapsed', 'layoutArea', 'moduleCode', 'rank', 'serial', 'showCouplings', 'showMultiplets', 'showPosition', 'showStructure', 'useMultiplePeakLists']
  currentMap['headerAttrs'] = aList
  aList = ['gridCell', 'gridSpan', 'name', 'listenLinks']
  currentMap['simpleAttrs'] = aList
  aList = ['windowPanelGroup']
  currentMap['optLinks'] = aList
  aList = ['parameters', 'panelAxes', 'actionLinks', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['actionLinks', 'panelAxes', 'parameters']
  currentMap['children'] = aList

  # Class WindowPanelNd
  currentMap = {}
  abstractTypes['WindowPanelNd'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00022'] = currentMap
  loadMaps['ANAY.WindowPanelNd'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelNd'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00022'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'panels'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.WindowPanelNd
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute WindowPanelNd.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute WindowPanelNd.aspectRatio
  currentMap = {}
  contentMap['aspectRatio'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00005'] = currentMap
  loadMaps['ANAY.WindowPanelNd.aspectRatio'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelNd.aspectRatio'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00005'
  currentMap['name'] = 'aspectRatio'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1.0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00007')

  # Attribute WindowPanelNd.gridCell
  contentMap['gridCell'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00020')

  # Attribute WindowPanelNd.gridSpan
  contentMap['gridSpan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00021')

  # Attribute WindowPanelNd.isCollapsed
  contentMap['isCollapsed'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00001')

  # Attribute WindowPanelNd.layoutArea
  contentMap['layoutArea'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00001')

  # Attribute WindowPanelNd.moduleCode
  contentMap['moduleCode'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00019')

  # Attribute WindowPanelNd.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-05-03-14:05:48_00001')

  # Attribute WindowPanelNd.rank
  contentMap['rank'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-04-18-15:31:21_00001')

  # Attribute WindowPanelNd.serial
  contentMap['serial'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00018')

  # Attribute WindowPanelNd.showCouplings
  contentMap['showCouplings'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00016')

  # Attribute WindowPanelNd.showCrosshairTrace
  currentMap = {}
  contentMap['showCrosshairTrace'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00006'] = currentMap
  loadMaps['ANAY.WindowPanelNd.showCrosshairTrace'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanelNd.showCrosshairTrace'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:04:35_00006'
  currentMap['name'] = 'showCrosshairTrace'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanelNd.showMultiplets
  contentMap['showMultiplets'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00015')

  # Attribute WindowPanelNd.showPosition
  contentMap['showPosition'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00017')

  # Attribute WindowPanelNd.showStructure
  contentMap['showStructure'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00014')

  # Attribute WindowPanelNd.useMultiplePeakLists
  contentMap['useMultiplePeakLists'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00013')

  # Role WindowPanelNd.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role WindowPanelNd.actionLinks
  contentMap['actionLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00013')

  # Role WindowPanelNd.listenLinks
  contentMap['listenLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00015')

  # Role WindowPanelNd.module
  contentMap['module'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00005')

  # Role WindowPanelNd.panelAxes
  contentMap['panelAxes'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00009')

  # Role WindowPanelNd.parameters
  contentMap['parameters'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00017')

  # Role WindowPanelNd.windowPanelGroup
  contentMap['windowPanelGroup'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00002')
  # End of WindowPanelNd

  currentMap = abstractTypes.get('WindowPanelNd')
  aList = ['aspectRatio', 'isCollapsed', 'layoutArea', 'moduleCode', 'rank', 'serial', 'showCouplings', 'showCrosshairTrace', 'showMultiplets', 'showPosition', 'showStructure', 'useMultiplePeakLists']
  currentMap['headerAttrs'] = aList
  aList = ['gridCell', 'gridSpan', 'name', 'listenLinks']
  currentMap['simpleAttrs'] = aList
  aList = ['windowPanelGroup']
  currentMap['optLinks'] = aList
  aList = ['parameters', 'panelAxes', 'actionLinks', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['actionLinks', 'panelAxes', 'parameters']
  currentMap['children'] = aList

  # Class WindowPanel1d
  currentMap = {}
  abstractTypes['WindowPanel1d'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00023'] = currentMap
  loadMaps['ANAY.WindowPanel1d'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00023'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'panels'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.WindowPanel1d
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute WindowPanel1d.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute WindowPanel1d.gridCell
  contentMap['gridCell'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00020')

  # Attribute WindowPanel1d.gridSpan
  contentMap['gridSpan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00021')

  # Attribute WindowPanel1d.isCollapsed
  contentMap['isCollapsed'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:57_00001')

  # Attribute WindowPanel1d.labelAngle
  currentMap = {}
  contentMap['labelAngle'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00001'] = currentMap
  loadMaps['ANAY.WindowPanel1d.labelAngle'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d.labelAngle'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00001'
  currentMap['name'] = 'labelAngle'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 45.0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute WindowPanel1d.layoutArea
  contentMap['layoutArea'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-08-16-17:30:29_00001')

  # Attribute WindowPanel1d.moduleCode
  contentMap['moduleCode'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00019')

  # Attribute WindowPanel1d.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-05-03-14:05:48_00001')

  # Attribute WindowPanel1d.rank
  contentMap['rank'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-04-18-15:31:21_00001')

  # Attribute WindowPanel1d.serial
  contentMap['serial'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00018')

  # Attribute WindowPanel1d.showAsStack
  currentMap = {}
  contentMap['showAsStack'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00021'] = currentMap
  loadMaps['ANAY.WindowPanel1d.showAsStack'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d.showAsStack'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00021'
  currentMap['name'] = 'showAsStack'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel1d.showCouplings
  contentMap['showCouplings'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00016')

  # Attribute WindowPanel1d.showIntegrals
  currentMap = {}
  contentMap['showIntegrals'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00020'] = currentMap
  loadMaps['ANAY.WindowPanel1d.showIntegrals'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d.showIntegrals'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00020'
  currentMap['name'] = 'showIntegrals'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel1d.showMultiplets
  contentMap['showMultiplets'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00015')

  # Attribute WindowPanel1d.showPeakPickLevel
  currentMap = {}
  contentMap['showPeakPickLevel'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-09-17-10:38:43_00001'] = currentMap
  loadMaps['ANAY.WindowPanel1d.showPeakPickLevel'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d.showPeakPickLevel'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-09-17-10:38:43_00001'
  currentMap['name'] = 'showPeakPickLevel'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel1d.showPosition
  contentMap['showPosition'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00017')

  # Attribute WindowPanel1d.showStructure
  contentMap['showStructure'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00014')

  # Attribute WindowPanel1d.stackOffset
  currentMap = {}
  contentMap['stackOffset'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00022'] = currentMap
  loadMaps['ANAY.WindowPanel1d.stackOffset'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d.stackOffset'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00022'
  currentMap['name'] = 'stackOffset'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [5.0, 5.0]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute WindowPanel1d.useAutoScale
  currentMap = {}
  contentMap['useAutoScale'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00019'] = currentMap
  loadMaps['ANAY.WindowPanel1d.useAutoScale'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d.useAutoScale'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00019'
  currentMap['name'] = 'useAutoScale'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute WindowPanel1d.useMultiplePeakLists
  contentMap['useMultiplePeakLists'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00013')

  # Attribute WindowPanel1d.valueScale
  currentMap = {}
  contentMap['valueScale'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00018'] = currentMap
  loadMaps['ANAY.WindowPanel1d.valueScale'] = currentMap
  currentMap['tag'] = 'ANAY.WindowPanel1d.valueScale'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00018'
  currentMap['name'] = 'valueScale'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 100000.0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00007')

  # Role WindowPanel1d.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role WindowPanel1d.actionLinks
  contentMap['actionLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00013')

  # Role WindowPanel1d.listenLinks
  contentMap['listenLinks'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00015')

  # Role WindowPanel1d.module
  contentMap['module'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00005')

  # Role WindowPanel1d.panelAxes
  contentMap['panelAxes'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:03:44_00009')

  # Role WindowPanel1d.parameters
  contentMap['parameters'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:02:23_00017')

  # Role WindowPanel1d.windowPanelGroup
  contentMap['windowPanelGroup'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:04:12_00002')
  # End of WindowPanel1d

  currentMap = abstractTypes.get('WindowPanel1d')
  aList = ['isCollapsed', 'labelAngle', 'layoutArea', 'moduleCode', 'rank', 'serial', 'showAsStack', 'showCouplings', 'showIntegrals', 'showMultiplets', 'showPeakPickLevel', 'showPosition', 'showStructure', 'useAutoScale', 'useMultiplePeakLists', 'valueScale']
  currentMap['headerAttrs'] = aList
  aList = ['gridCell', 'gridSpan', 'name', 'stackOffset', 'listenLinks']
  currentMap['simpleAttrs'] = aList
  aList = ['windowPanelGroup']
  currentMap['optLinks'] = aList
  aList = ['parameters', 'panelAxes', 'actionLinks', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['actionLinks', 'panelAxes', 'parameters']
  currentMap['children'] = aList

  # Out-of-package link to ActionLink
  currentMap = {}
  exolinks['ActionLink'] = currentMap
  loadMaps['ANAY.exo-ActionLink'] = currentMap
  currentMap['tag'] = 'ANAY.exo-ActionLink'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00016'
  currentMap['name'] = 'ActionLink'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.ActionLink
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to ActionLinkParameter
  currentMap = {}
  exolinks['ActionLinkParameter'] = currentMap
  loadMaps['ANAY.exo-ActionLinkParameter'] = currentMap
  currentMap['tag'] = 'ANAY.exo-ActionLinkParameter'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00028'
  currentMap['name'] = 'ActionLinkParameter'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.ActionLinkParameter
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to AxisGroup
  currentMap = {}
  exolinks['AxisGroup'] = currentMap
  loadMaps['ANAY.exo-AxisGroup'] = currentMap
  currentMap['tag'] = 'ANAY.exo-AxisGroup'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00020'
  currentMap['name'] = 'AxisGroup'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.AxisGroup
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to Layout
  currentMap = {}
  exolinks['Layout'] = currentMap
  loadMaps['ANAY.exo-Layout'] = currentMap
  currentMap['tag'] = 'ANAY.exo-Layout'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00011'
  currentMap['name'] = 'Layout'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.Layout
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))

  # Out-of-package link to LayoutParameter
  currentMap = {}
  exolinks['LayoutParameter'] = currentMap
  loadMaps['ANAY.exo-LayoutParameter'] = currentMap
  currentMap['tag'] = 'ANAY.exo-LayoutParameter'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00030'
  currentMap['name'] = 'LayoutParameter'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.LayoutParameter
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to Mark
  currentMap = {}
  exolinks['Mark'] = currentMap
  loadMaps['ANAY.exo-Mark'] = currentMap
  currentMap['tag'] = 'ANAY.exo-Mark'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00012'
  currentMap['name'] = 'Mark'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.Mark
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to PanelAxis
  currentMap = {}
  exolinks['PanelAxis'] = currentMap
  loadMaps['ANAY.exo-PanelAxis'] = currentMap
  currentMap['tag'] = 'ANAY.exo-PanelAxis'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00019'
  currentMap['name'] = 'PanelAxis'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.PanelAxis
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to PanelGroupParameter
  currentMap = {}
  exolinks['PanelGroupParameter'] = currentMap
  loadMaps['ANAY.exo-PanelGroupParameter'] = currentMap
  currentMap['tag'] = 'ANAY.exo-PanelGroupParameter'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00031'
  currentMap['name'] = 'PanelGroupParameter'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.PanelGroupParameter
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to PanelParameter
  currentMap = {}
  exolinks['PanelParameter'] = currentMap
  loadMaps['ANAY.exo-PanelParameter'] = currentMap
  currentMap['tag'] = 'ANAY.exo-PanelParameter'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00029'
  currentMap['name'] = 'PanelParameter'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.PanelParameter
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to WindowPanelGroup
  currentMap = {}
  exolinks['WindowPanelGroup'] = currentMap
  loadMaps['ANAY.exo-WindowPanelGroup'] = currentMap
  currentMap['tag'] = 'ANAY.exo-WindowPanelGroup'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00021'
  currentMap['name'] = 'WindowPanelGroup'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.WindowPanelGroup
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to MarkDim
  currentMap = {}
  exolinks['MarkDim'] = currentMap
  loadMaps['ANAY.exo-MarkDim'] = currentMap
  currentMap['tag'] = 'ANAY.exo-MarkDim'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00013'
  currentMap['name'] = 'MarkDim'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.MarkDim
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to Ruler
  currentMap = {}
  exolinks['Ruler'] = currentMap
  loadMaps['ANAY.exo-Ruler'] = currentMap
  currentMap['tag'] = 'ANAY.exo-Ruler'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00014'
  currentMap['name'] = 'Ruler'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.Ruler
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to ModulePanel
  currentMap = {}
  exolinks['ModulePanel'] = currentMap
  loadMaps['ANAY.exo-ModulePanel'] = currentMap
  currentMap['tag'] = 'ANAY.exo-ModulePanel'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00018'
  currentMap['name'] = 'ModulePanel'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.ModulePanel
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to WindowPanelNd
  currentMap = {}
  exolinks['WindowPanelNd'] = currentMap
  loadMaps['ANAY.exo-WindowPanelNd'] = currentMap
  currentMap['tag'] = 'ANAY.exo-WindowPanelNd'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00022'
  currentMap['name'] = 'WindowPanelNd'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.WindowPanelNd
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to WindowPanel1d
  currentMap = {}
  exolinks['WindowPanel1d'] = currentMap
  loadMaps['ANAY.exo-WindowPanel1d'] = currentMap
  currentMap['tag'] = 'ANAY.exo-WindowPanel1d'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00023'
  currentMap['name'] = 'WindowPanel1d'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisLayout.WindowPanel1d
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
