"""
#######################################################################

CCPN Data Model version 2.1.2

Autogenerated by PyXmlMapWrite revision 1.29 on Mon Mar  2 17:24:10 2015
  from data model element ccpnmr.AnalysisWindow revision ?

#######################################################################
======================COPYRIGHT/LICENSE START==========================

AnalysisWindow.py: python XML-I/O-mapping for CCPN data model, MetaPackage ccpnmr.AnalysisWindow

Copyright (C) 2007  (CCPN Project)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
 
A copy of this license can be found in ../../../license/LGPL.license
 
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.
 
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- CCPN website (http://www.ccpn.ac.uk/)

- email: ccpn@bioc.cam.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
Rasmus H. Fogh, Wayne Boucher, Wim F. Vranken, Anne
Pajon, Tim J. Stevens, T.N. Bhat, John Westbrook, John M.C. Ionides and
Ernest D. Laue (2005). A framework for scientific data modeling and automated
software development. Bioinformatics 21, 1678-1684.


This file was generated with the Memops software generation framework,
and contains original contributions embedded in the framework

===========================REFERENCE END===============================
"""
from memops.general.Constants import baseDataTypeModule as basicDataTypes
# 
#  Current package api
import ccpnmr.api.AnalysisWindow

def makeMapping(globalMap):
  """
  generates XML I/O mapping for package ANAW, adding it to globalMap
  """
  
  from memops.xml.Implementation import bool2str, str2bool

  # Set up top level dictionaries
  loadMaps = globalMap.get('loadMaps')
  mapsByGuid = globalMap.get('mapsByGuid')

  abstractTypes = globalMap.get('ANAW').get('abstractTypes')
  exolinks = globalMap.get('ANAW').get('exolinks')

  # Class AbstractModule
  currentMap = {}
  abstractTypes['AbstractModule'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00004'] = currentMap
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00004'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'modules'
  currentMap['objkey'] = 'code'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.AbstractModule
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AbstractModule.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AbstractModule.code
  currentMap = {}
  contentMap['code'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00008'] = currentMap
  loadMaps['ANAW.AbstractModule.code'] = currentMap
  currentMap['tag'] = 'ANAW.AbstractModule.code'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00008'
  currentMap['name'] = 'code'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute AbstractModule.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00001'] = currentMap
  loadMaps['ANAW.AbstractModule.details'] = currentMap
  currentMap['tag'] = 'ANAW.AbstractModule.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00001'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute AbstractModule.helpUrl
  currentMap = {}
  contentMap['helpUrl'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00010'] = currentMap
  loadMaps['ANAW.AbstractModule.helpUrl'] = currentMap
  currentMap['tag'] = 'ANAW.AbstractModule.helpUrl'
  currentMap['type'] = 'dobj'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00010'
  currentMap['name'] = 'helpUrl'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('IMPL').get('abstractTypes')

  # Attribute AbstractModule.keywords
  currentMap = {}
  contentMap['keywords'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00002'] = currentMap
  loadMaps['ANAW.AbstractModule.keywords'] = currentMap
  currentMap['tag'] = 'ANAW.AbstractModule.keywords'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00002'
  currentMap['name'] = 'keywords'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute AbstractModule.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00009'] = currentMap
  loadMaps['ANAW.AbstractModule.name'] = currentMap
  currentMap['tag'] = 'ANAW.AbstractModule.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00009'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role AbstractModule.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role AbstractModule.parameters
  currentMap = {}
  contentMap['parameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00007'] = currentMap
  loadMaps['ANAW.AbstractModule.parameters'] = currentMap
  currentMap['tag'] = 'ANAW.AbstractModule.parameters'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00007'
  currentMap['name'] = 'parameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAW').get('abstractTypes')
  # End of AbstractModule

  currentMap = abstractTypes.get('AbstractModule')
  aList = ['code']
  currentMap['headerAttrs'] = aList
  aList = ['details', 'keywords', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['parameters', 'access', 'helpUrl', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['parameters']
  currentMap['children'] = aList

  # Class AnalysisWindowStore
  currentMap = {}
  abstractTypes['AnalysisWindowStore'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-10:49:23_00002'] = currentMap
  loadMaps['ANAW.AnalysisWindowStore'] = currentMap
  currentMap['tag'] = 'ANAW.AnalysisWindowStore'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-10:49:23_00002'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'analysisWindowStores'
  currentMap['isTop'] = True
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.AnalysisWindowStore
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AnalysisWindowStore.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AnalysisWindowStore.createdBy
  contentMap['createdBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00002__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute AnalysisWindowStore.guid
  contentMap['guid'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:26_00002')

  # Attribute AnalysisWindowStore.isModifiable
  contentMap['isModifiable'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-17-14:16:26_00010__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute AnalysisWindowStore.lastUnlockedBy
  contentMap['lastUnlockedBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00003__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute AnalysisWindowStore.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00017'] = currentMap
  loadMaps['ANAW.AnalysisWindowStore.name'] = currentMap
  currentMap['tag'] = 'ANAW.AnalysisWindowStore.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00017'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Role AnalysisWindowStore.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role AnalysisWindowStore.axisTypes
  currentMap = {}
  contentMap['axisTypes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00014'] = currentMap
  loadMaps['ANAW.AnalysisWindowStore.axisTypes'] = currentMap
  currentMap['tag'] = 'ANAW.AnalysisWindowStore.axisTypes'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00014'
  currentMap['name'] = 'axisTypes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAW').get('abstractTypes')

  # Role AnalysisWindowStore.axisUnits
  currentMap = {}
  contentMap['axisUnits'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00016'] = currentMap
  loadMaps['ANAW.AnalysisWindowStore.axisUnits'] = currentMap
  currentMap['tag'] = 'ANAW.AnalysisWindowStore.axisUnits'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00016'
  currentMap['name'] = 'axisUnits'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAW').get('abstractTypes')

  # Role AnalysisWindowStore.modules
  currentMap = {}
  contentMap['modules'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00012'] = currentMap
  loadMaps['ANAW.AnalysisWindowStore.modules'] = currentMap
  currentMap['tag'] = 'ANAW.AnalysisWindowStore.modules'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00012'
  currentMap['name'] = 'modules'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('ANAW').get('abstractTypes')
  # End of AnalysisWindowStore

  currentMap = abstractTypes.get('AnalysisWindowStore')
  aList = ['createdBy', 'guid', 'isModifiable', 'lastUnlockedBy', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['modules', 'axisUnits', 'axisTypes', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['axisTypes', 'axisUnits', 'modules']
  currentMap['children'] = aList

  # Class AxisType
  currentMap = {}
  abstractTypes['AxisType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00010'] = currentMap
  loadMaps['ANAW.AxisType'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00010'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'axisTypes'
  currentMap['objkey'] = 'code'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.AxisType
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AxisType.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AxisType.code
  currentMap = {}
  contentMap['code'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00022'] = currentMap
  loadMaps['ANAW.AxisType.code'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.code'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00022'
  currentMap['name'] = 'code'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute AxisType.diagonalExclusion
  currentMap = {}
  contentMap['diagonalExclusion'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00023'] = currentMap
  loadMaps['ANAW.AxisType.diagonalExclusion'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.diagonalExclusion'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00023'
  currentMap['name'] = 'diagonalExclusion'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 0.0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00009')

  # Attribute AxisType.isSampled
  currentMap = {}
  contentMap['isSampled'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00024'] = currentMap
  loadMaps['ANAW.AxisType.isSampled'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.isSampled'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00024'
  currentMap['name'] = 'isSampled'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute AxisType.isotopeCodes
  currentMap = {}
  contentMap['isotopeCodes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00025'] = currentMap
  loadMaps['ANAW.AxisType.isotopeCodes'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.isotopeCodes'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00025'
  currentMap['name'] = 'isotopeCodes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute AxisType.measurementType
  currentMap = {}
  contentMap['measurementType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00026'] = currentMap
  loadMaps['ANAW.AxisType.measurementType'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.measurementType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00026'
  currentMap['name'] = 'measurementType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['default'] = 'Shift'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:45_00030')

  # Attribute AxisType.numDecimals
  currentMap = {}
  contentMap['numDecimals'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00027'] = currentMap
  loadMaps['ANAW.AxisType.numDecimals'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.numDecimals'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00027'
  currentMap['name'] = 'numDecimals'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['proc'] = 'direct'
  currentMap['default'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute AxisType.region
  currentMap = {}
  contentMap['region'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00028'] = currentMap
  loadMaps['ANAW.AxisType.region'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.region'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00028'
  currentMap['name'] = 'region'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [0.0, 1.0]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Role AxisType.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role AxisType.axisUnits
  currentMap = {}
  contentMap['axisUnits'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00021'] = currentMap
  loadMaps['ANAW.AxisType.axisUnits'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.axisUnits'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00021'
  currentMap['name'] = 'axisUnits'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role AxisType.windowAxes
  currentMap = {}
  contentMap['windowAxes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00019'] = currentMap
  loadMaps['ANAW.AxisType.windowAxes'] = currentMap
  currentMap['tag'] = 'ANAW.AxisType.windowAxes'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00019'
  currentMap['name'] = 'windowAxes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of AxisType

  currentMap = abstractTypes.get('AxisType')
  aList = ['code', 'diagonalExclusion', 'isSampled', 'numDecimals']
  currentMap['headerAttrs'] = aList
  aList = ['isotopeCodes', 'measurementType', 'region', 'axisUnits', 'windowAxes']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class AxisUnit
  currentMap = {}
  abstractTypes['AxisUnit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00026'] = currentMap
  loadMaps['ANAW.AxisUnit'] = currentMap
  currentMap['tag'] = 'ANAW.AxisUnit'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00026'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'axisUnits'
  currentMap['objkey'] = 'unit'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.AxisUnit
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AxisUnit.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AxisUnit.isBackwards
  currentMap = {}
  contentMap['isBackwards'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00032'] = currentMap
  loadMaps['ANAW.AxisUnit.isBackwards'] = currentMap
  currentMap['tag'] = 'ANAW.AxisUnit.isBackwards'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00032'
  currentMap['name'] = 'isBackwards'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute AxisUnit.unit
  currentMap = {}
  contentMap['unit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00031'] = currentMap
  loadMaps['ANAW.AxisUnit.unit'] = currentMap
  currentMap['tag'] = 'ANAW.AxisUnit.unit'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00031'
  currentMap['name'] = 'unit'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Role AxisUnit.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role AxisUnit.axisTypes
  currentMap = {}
  contentMap['axisTypes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00020'] = currentMap
  loadMaps['ANAW.AxisUnit.axisTypes'] = currentMap
  currentMap['tag'] = 'ANAW.AxisUnit.axisTypes'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00020'
  currentMap['name'] = 'axisTypes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role AxisUnit.windowAxes
  currentMap = {}
  contentMap['windowAxes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00030'] = currentMap
  loadMaps['ANAW.AxisUnit.windowAxes'] = currentMap
  currentMap['tag'] = 'ANAW.AxisUnit.windowAxes'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00030'
  currentMap['name'] = 'windowAxes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of AxisUnit

  currentMap = abstractTypes.get('AxisUnit')
  aList = ['isBackwards', 'unit']
  currentMap['headerAttrs'] = aList
  aList = ['axisTypes', 'windowAxes']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class ModuleParameter
  currentMap = {}
  abstractTypes['ModuleParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00027'] = currentMap
  loadMaps['ANAW.ModuleParameter'] = currentMap
  currentMap['tag'] = 'ANAW.ModuleParameter'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00027'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'parameters'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.ModuleParameter
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ModuleParameter.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ModuleParameter.booleanValue
  contentMap['booleanValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00008')

  # Attribute ModuleParameter.description
  currentMap = {}
  contentMap['description'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00008'] = currentMap
  loadMaps['ANAW.ModuleParameter.description'] = currentMap
  currentMap['tag'] = 'ANAW.ModuleParameter.description'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00008'
  currentMap['name'] = 'description'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ModuleParameter.floatValue
  contentMap['floatValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00007')

  # Attribute ModuleParameter.intValue
  contentMap['intValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00006')

  # Attribute ModuleParameter.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00007'] = currentMap
  loadMaps['ANAW.ModuleParameter.name'] = currentMap
  currentMap['tag'] = 'ANAW.ModuleParameter.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00007'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute ModuleParameter.textValue
  contentMap['textValue'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2007-11-13-15:55:55_00005')

  # Role ModuleParameter.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of ModuleParameter

  currentMap = abstractTypes.get('ModuleParameter')
  aList = ['booleanValue', 'floatValue', 'intValue', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['description', 'textValue']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class WindowAxis
  currentMap = {}
  abstractTypes['WindowAxis'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00007'] = currentMap
  loadMaps['ANAW.WindowAxis'] = currentMap
  currentMap['tag'] = 'ANAW.WindowAxis'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00007'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'axes'
  currentMap['objkey'] = 'label'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.WindowAxis
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute WindowAxis.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute WindowAxis.label
  currentMap = {}
  contentMap['label'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00015'] = currentMap
  loadMaps['ANAW.WindowAxis.label'] = currentMap
  currentMap['tag'] = 'ANAW.WindowAxis.label'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00015'
  currentMap['name'] = 'label'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Role WindowAxis.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role WindowAxis.axisType
  currentMap = {}
  contentMap['axisType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00018'] = currentMap
  loadMaps['ANAW.WindowAxis.axisType'] = currentMap
  currentMap['tag'] = 'ANAW.WindowAxis.axisType'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00018'
  currentMap['name'] = 'axisType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['copyOverride'] = True

  # Role WindowAxis.axisUnit
  currentMap = {}
  contentMap['axisUnit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00029'] = currentMap
  loadMaps['ANAW.WindowAxis.axisUnit'] = currentMap
  currentMap['tag'] = 'ANAW.WindowAxis.axisUnit'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00029'
  currentMap['name'] = 'axisUnit'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['copyOverride'] = True

  # Role WindowAxis.boundAxis
  currentMap = {}
  contentMap['boundAxis'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00014'] = currentMap
  loadMaps['ANAW.WindowAxis.boundAxis'] = currentMap
  currentMap['tag'] = 'ANAW.WindowAxis.boundAxis'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00014'
  currentMap['name'] = 'boundAxis'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of WindowAxis

  currentMap = abstractTypes.get('WindowAxis')
  aList = ['label']
  currentMap['headerAttrs'] = aList
  aList = ['boundAxis']
  currentMap['simpleAttrs'] = aList
  aList = ['axisType', 'axisUnit']
  currentMap['optLinks'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class Module
  currentMap = {}
  abstractTypes['Module'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00005'] = currentMap
  loadMaps['ANAW.Module'] = currentMap
  currentMap['tag'] = 'ANAW.Module'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00005'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'modules'
  currentMap['objkey'] = 'code'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.Module
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Module.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Module.code
  contentMap['code'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00008')

  # Attribute Module.defaultGridCell
  currentMap = {}
  contentMap['defaultGridCell'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00001'] = currentMap
  loadMaps['ANAW.Module.defaultGridCell'] = currentMap
  currentMap['tag'] = 'ANAW.Module.defaultGridCell'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00001'
  currentMap['name'] = 'defaultGridCell'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [0, 0]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute Module.defaultGridSpan
  currentMap = {}
  contentMap['defaultGridSpan'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00002'] = currentMap
  loadMaps['ANAW.Module.defaultGridSpan'] = currentMap
  currentMap['tag'] = 'ANAW.Module.defaultGridSpan'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00002'
  currentMap['name'] = 'defaultGridSpan'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['default'] = [1, 1]
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00001')

  # Attribute Module.defaultSize
  currentMap = {}
  contentMap['defaultSize'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00033'] = currentMap
  loadMaps['ANAW.Module.defaultSize'] = currentMap
  currentMap['tag'] = 'ANAW.Module.defaultSize'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00033'
  currentMap['name'] = 'defaultSize'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute Module.details
  contentMap['details'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00001')

  # Attribute Module.helpUrl
  contentMap['helpUrl'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00010')

  # Attribute Module.isCollapsible
  currentMap = {}
  contentMap['isCollapsible'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00006'] = currentMap
  loadMaps['ANAW.Module.isCollapsible'] = currentMap
  currentMap['tag'] = 'ANAW.Module.isCollapsible'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00006'
  currentMap['name'] = 'isCollapsible'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Module.isModal
  currentMap = {}
  contentMap['isModal'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00003'] = currentMap
  loadMaps['ANAW.Module.isModal'] = currentMap
  currentMap['tag'] = 'ANAW.Module.isModal'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00003'
  currentMap['name'] = 'isModal'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Module.isPopout
  currentMap = {}
  contentMap['isPopout'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00004'] = currentMap
  loadMaps['ANAW.Module.isPopout'] = currentMap
  currentMap['tag'] = 'ANAW.Module.isPopout'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00004'
  currentMap['name'] = 'isPopout'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Module.isWizard
  currentMap = {}
  contentMap['isWizard'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00005'] = currentMap
  loadMaps['ANAW.Module.isWizard'] = currentMap
  currentMap['tag'] = 'ANAW.Module.isWizard'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00005'
  currentMap['name'] = 'isWizard'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute Module.keywords
  contentMap['keywords'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00002')

  # Attribute Module.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00009')

  # Role Module.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role Module.parameters
  contentMap['parameters'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00007')
  # End of Module

  currentMap = abstractTypes.get('Module')
  aList = ['code', 'isCollapsible', 'isModal', 'isPopout', 'isWizard']
  currentMap['headerAttrs'] = aList
  aList = ['defaultGridCell', 'defaultGridSpan', 'defaultSize', 'details', 'keywords', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['parameters', 'access', 'helpUrl', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['parameters']
  currentMap['children'] = aList

  # Class Window
  currentMap = {}
  abstractTypes['Window'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00006'] = currentMap
  loadMaps['ANAW.Window'] = currentMap
  currentMap['tag'] = 'ANAW.Window'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00006'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'modules'
  currentMap['objkey'] = 'code'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.Window
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Window.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Window.code
  contentMap['code'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00008')

  # Attribute Window.details
  contentMap['details'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00001')

  # Attribute Window.helpUrl
  contentMap['helpUrl'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00010')

  # Attribute Window.keywords
  contentMap['keywords'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2012-09-10-14:34:37_00002')

  # Attribute Window.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00009')

  # Role Window.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role Window.axes
  currentMap = {}
  contentMap['axes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00010'] = currentMap
  loadMaps['ANAW.Window.axes'] = currentMap
  currentMap['tag'] = 'ANAW.Window.axes'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-11:01:45_00010'
  currentMap['name'] = 'axes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('ANAW').get('abstractTypes')

  # Role Window.parameters
  contentMap['parameters'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-11-30-11:00:37_00007')
  # End of Window

  currentMap = abstractTypes.get('Window')
  aList = ['code']
  currentMap['headerAttrs'] = aList
  aList = ['details', 'keywords', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['parameters', 'axes', 'access', 'helpUrl', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['axes', 'parameters']
  currentMap['children'] = aList

  # Out-of-package link to AnalysisWindowStore
  currentMap = {}
  exolinks['AnalysisWindowStore'] = currentMap
  loadMaps['ANAW.exo-AnalysisWindowStore'] = currentMap
  currentMap['tag'] = 'ANAW.exo-AnalysisWindowStore'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-30-10:49:23_00002'
  currentMap['name'] = 'AnalysisWindowStore'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.AnalysisWindowStore
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))

  # Out-of-package link to AxisType
  currentMap = {}
  exolinks['AxisType'] = currentMap
  loadMaps['ANAW.exo-AxisType'] = currentMap
  currentMap['tag'] = 'ANAW.exo-AxisType'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00010'
  currentMap['name'] = 'AxisType'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.AxisType
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to AxisUnit
  currentMap = {}
  exolinks['AxisUnit'] = currentMap
  loadMaps['ANAW.exo-AxisUnit'] = currentMap
  currentMap['tag'] = 'ANAW.exo-AxisUnit'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00026'
  currentMap['name'] = 'AxisUnit'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.AxisUnit
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to ModuleParameter
  currentMap = {}
  exolinks['ModuleParameter'] = currentMap
  loadMaps['ANAW.exo-ModuleParameter'] = currentMap
  currentMap['tag'] = 'ANAW.exo-ModuleParameter'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00027'
  currentMap['name'] = 'ModuleParameter'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.ModuleParameter
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to WindowAxis
  currentMap = {}
  exolinks['WindowAxis'] = currentMap
  loadMaps['ANAW.exo-WindowAxis'] = currentMap
  currentMap['tag'] = 'ANAW.exo-WindowAxis'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00007'
  currentMap['name'] = 'WindowAxis'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.WindowAxis
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to Module
  currentMap = {}
  exolinks['Module'] = currentMap
  loadMaps['ANAW.exo-Module'] = currentMap
  currentMap['tag'] = 'ANAW.exo-Module'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00005'
  currentMap['name'] = 'Module'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.Module
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to Window
  currentMap = {}
  exolinks['Window'] = currentMap
  loadMaps['ANAW.exo-Window'] = currentMap
  currentMap['tag'] = 'ANAW.exo-Window'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-11-16-17:07:15_00006'
  currentMap['name'] = 'Window'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmr.api.AnalysisWindow.Window
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))
