del --force *.pyd
copy ..\\..\\..\\c\\memops\\global\\BlockFile.pyd BlockFile.pyd
copy ..\\..\\..\\c\\memops\\global\\FitMethod.pyd FitMethod.pyd
copy ..\\..\\..\\c\\memops\\global\\GlHandler.pyd GlHandler.pyd
copy ..\\..\\..\\c\\memops\\global\\MemCache.pyd MemCache.pyd
copy ..\\..\\..\\c\\memops\\global\\PdfHandler.pyd PdfHandler.pyd
copy ..\\..\\..\\c\\memops\\global\\PsHandler.pyd PsHandler.pyd
copy ..\\..\\..\\c\\memops\\global\\StoreFile.pyd StoreFile.pyd
copy ..\\..\\..\\c\\memops\\global\\StoreHandler.pyd StoreHandler.pyd
copy ..\\..\\..\\c\\memops\\global\\TkHandler.pyd TkHandler.pyd
