"""
#######################################################################

CCPN Data Model version 2.1.2

Autogenerated by PyXmlMapWrite revision 1.29 on Mon Mar  2 17:24:14 2015
  from data model element cambridge.WmsProtocol revision ?

#######################################################################
======================COPYRIGHT/LICENSE START==========================

WmsProtocol.py: python XML-I/O-mapping for CCPN data model, MetaPackage cambridge.WmsProtocol

Copyright (C) 2007  (CCPN Project)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
 
A copy of this license can be found in ../../../license/LGPL.license
 
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.
 
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- CCPN website (http://www.ccpn.ac.uk/)

- email: ccpn@bioc.cam.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
Rasmus H. Fogh, Wayne Boucher, Wim F. Vranken, Anne
Pajon, Tim J. Stevens, T.N. Bhat, John Westbrook, John M.C. Ionides and
Ernest D. Laue (2005). A framework for scientific data modeling and automated
software development. Bioinformatics 21, 1678-1684.


This file was generated with the Memops software generation framework,
and contains original contributions embedded in the framework

===========================REFERENCE END===============================
"""
from memops.general.Constants import baseDataTypeModule as basicDataTypes
# 
#  Current package api
import cambridge.api.WmsProtocol

def makeMapping(globalMap):
  """
  generates XML I/O mapping for package WMSP, adding it to globalMap
  """
  
  from memops.xml.Implementation import bool2str, str2bool

  # Set up top level dictionaries
  loadMaps = globalMap.get('loadMaps')
  mapsByGuid = globalMap.get('mapsByGuid')

  abstractTypes = globalMap.get('WMSP').get('abstractTypes')
  exolinks = globalMap.get('WMSP').get('exolinks')

  # DataType ParamType
  currentMap = {}
  abstractTypes['ParamType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00006'] = currentMap
  loadMaps['WMSP.ParamType'] = currentMap
  currentMap['tag'] = 'WMSP.ParamType'
  currentMap['type'] = 'simple'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00006'
  currentMap['toStr'] = 'text'
  currentMap['cnvrt'] = 'text'

  # Class EnumValue
  currentMap = {}
  abstractTypes['EnumValue'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00003'] = currentMap
  loadMaps['WMSP.EnumValue'] = currentMap
  currentMap['tag'] = 'WMSP.EnumValue'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00003'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'enumValues'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = cambridge.api.WmsProtocol.EnumValue
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute EnumValue.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute EnumValue.label
  currentMap = {}
  contentMap['label'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00002'] = currentMap
  loadMaps['WMSP.EnumValue.label'] = currentMap
  currentMap['tag'] = 'WMSP.EnumValue.label'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00002'
  currentMap['name'] = 'label'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute EnumValue.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00001'] = currentMap
  loadMaps['WMSP.EnumValue.serial'] = currentMap
  currentMap['tag'] = 'WMSP.EnumValue.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00001'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute EnumValue.value
  currentMap = {}
  contentMap['value'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-05-26-12:12:14_00001'] = currentMap
  loadMaps['WMSP.EnumValue.value'] = currentMap
  currentMap['tag'] = 'WMSP.EnumValue.value'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-05-26-12:12:14_00001'
  currentMap['name'] = 'value'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Role EnumValue.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of EnumValue

  currentMap = abstractTypes.get('EnumValue')
  aList = ['serial']
  currentMap['headerAttrs'] = aList
  aList = ['label', 'value']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class InterfaceObject
  currentMap = {}
  abstractTypes['InterfaceObject'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-10-11-16:36:18_00003'] = currentMap
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-11-16:36:18_00003'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.InterfaceObject
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute InterfaceObject.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute InterfaceObject.col
  currentMap = {}
  contentMap['col'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00012'] = currentMap
  loadMaps['WMSP.InterfaceObject.col'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceObject.col'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00012'
  currentMap['name'] = 'col'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute InterfaceObject.colspan
  currentMap = {}
  contentMap['colspan'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00014'] = currentMap
  loadMaps['WMSP.InterfaceObject.colspan'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceObject.colspan'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00014'
  currentMap['name'] = 'colspan'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute InterfaceObject.interfaceGroup
  currentMap = {}
  contentMap['interfaceGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00003'] = currentMap
  loadMaps['WMSP.InterfaceObject.interfaceGroup'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceObject.interfaceGroup'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00003'
  currentMap['name'] = 'interfaceGroup'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute InterfaceObject.row
  currentMap = {}
  contentMap['row'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00011'] = currentMap
  loadMaps['WMSP.InterfaceObject.row'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceObject.row'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00011'
  currentMap['name'] = 'row'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute InterfaceObject.rowspan
  currentMap = {}
  contentMap['rowspan'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00013'] = currentMap
  loadMaps['WMSP.InterfaceObject.rowspan'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceObject.rowspan'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00013'
  currentMap['name'] = 'rowspan'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Role InterfaceObject.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of InterfaceObject

  currentMap = abstractTypes.get('InterfaceObject')
  aList = ['col', 'colspan', 'row', 'rowspan']
  currentMap['headerAttrs'] = aList
  aList = ['interfaceGroup']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class ProtocolAccess
  currentMap = {}
  abstractTypes['ProtocolAccess'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00005'] = currentMap
  loadMaps['WMSP.ProtocolAccess'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolAccess'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00005'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'protocolAccesss'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolAccess
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ProtocolAccess.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ProtocolAccess.localUserName
  currentMap = {}
  contentMap['localUserName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-10-13:46:55_00003'] = currentMap
  loadMaps['WMSP.ProtocolAccess.localUserName'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolAccess.localUserName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-10-13:46:55_00003'
  currentMap['name'] = 'localUserName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ProtocolAccess.password
  currentMap = {}
  contentMap['password'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00018'] = currentMap
  loadMaps['WMSP.ProtocolAccess.password'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolAccess.password'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00018'
  currentMap['name'] = 'password'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ProtocolAccess.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00016'] = currentMap
  loadMaps['WMSP.ProtocolAccess.serial'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolAccess.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00016'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute ProtocolAccess.userName
  currentMap = {}
  contentMap['userName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00017'] = currentMap
  loadMaps['WMSP.ProtocolAccess.userName'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolAccess.userName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00017'
  currentMap['name'] = 'userName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role ProtocolAccess.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of ProtocolAccess

  currentMap = abstractTypes.get('ProtocolAccess')
  aList = ['serial']
  currentMap['headerAttrs'] = aList
  aList = ['localUserName', 'password', 'userName']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class ProtocolInterface
  currentMap = {}
  abstractTypes['ProtocolInterface'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00001'] = currentMap
  loadMaps['WMSP.ProtocolInterface'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolInterface'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00001'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'protocolInterfaces'
  currentMap['objkey'] = 'name'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolInterface
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ProtocolInterface.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ProtocolInterface.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00029'] = currentMap
  loadMaps['WMSP.ProtocolInterface.details'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolInterface.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00029'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute ProtocolInterface.info
  currentMap = {}
  contentMap['info'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00028'] = currentMap
  loadMaps['WMSP.ProtocolInterface.info'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolInterface.info'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00028'
  currentMap['name'] = 'info'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute ProtocolInterface.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00026'] = currentMap
  loadMaps['WMSP.ProtocolInterface.name'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolInterface.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00026'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ProtocolInterface.title
  currentMap = {}
  contentMap['title'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00027'] = currentMap
  loadMaps['WMSP.ProtocolInterface.title'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolInterface.title'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00027'
  currentMap['name'] = 'title'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role ProtocolInterface.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role ProtocolInterface.interfaceLabels
  currentMap = {}
  contentMap['interfaceLabels'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-10-11-16:36:21_00002'] = currentMap
  loadMaps['WMSP.ProtocolInterface.interfaceLabels'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolInterface.interfaceLabels'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-11-16:36:21_00002'
  currentMap['name'] = 'interfaceLabels'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('WMSP').get('abstractTypes')

  # Role ProtocolInterface.interfaceParameters
  currentMap = {}
  contentMap['interfaceParameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00023'] = currentMap
  loadMaps['WMSP.ProtocolInterface.interfaceParameters'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolInterface.interfaceParameters'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00023'
  currentMap['name'] = 'interfaceParameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('WMSP').get('abstractTypes')
  # End of ProtocolInterface

  currentMap = abstractTypes.get('ProtocolInterface')
  aList = ['details', 'info', 'name', 'title']
  currentMap['simpleAttrs'] = aList
  aList = ['interfaceParameters', 'interfaceLabels', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['interfaceLabels', 'interfaceParameters']
  currentMap['children'] = aList

  # Class ProtocolParameter
  currentMap = {}
  abstractTypes['ProtocolParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00003'] = currentMap
  loadMaps['WMSP.ProtocolParameter'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00003'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'protocolParameters'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolParameter
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ProtocolParameter.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ProtocolParameter.code
  currentMap = {}
  contentMap['code'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-20-10:42:03_00001'] = currentMap
  loadMaps['WMSP.ProtocolParameter.code'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.code'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-20-10:42:03_00001'
  currentMap['name'] = 'code'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute ProtocolParameter.defaultStrings
  currentMap = {}
  contentMap['defaultStrings'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00008'] = currentMap
  loadMaps['WMSP.ProtocolParameter.defaultStrings'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.defaultStrings'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00008'
  currentMap['name'] = 'defaultStrings'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute ProtocolParameter.hicard
  currentMap = {}
  contentMap['hicard'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-06-09-13:36:54_00002'] = currentMap
  loadMaps['WMSP.ProtocolParameter.hicard'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.hicard'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-06-09-13:36:54_00002'
  currentMap['name'] = 'hicard'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['proc'] = 'direct'
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute ProtocolParameter.ioRole
  currentMap = {}
  contentMap['ioRole'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-20-14:35:13_00005'] = currentMap
  loadMaps['WMSP.ProtocolParameter.ioRole'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.ioRole'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-20-14:35:13_00005'
  currentMap['name'] = 'ioRole'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 'input'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2009-04-16-16:23:57_00007')

  # Attribute ProtocolParameter.locard
  currentMap = {}
  contentMap['locard'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-06-09-13:36:54_00001'] = currentMap
  loadMaps['WMSP.ProtocolParameter.locard'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.locard'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-06-09-13:36:54_00001'
  currentMap['name'] = 'locard'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute ProtocolParameter.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00009'] = currentMap
  loadMaps['WMSP.ProtocolParameter.name'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00009'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ProtocolParameter.paramType
  currentMap = {}
  contentMap['paramType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00001'] = currentMap
  loadMaps['WMSP.ProtocolParameter.paramType'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.paramType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00001'
  currentMap['name'] = 'paramType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute ProtocolParameter.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00019'] = currentMap
  loadMaps['WMSP.ProtocolParameter.serial'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00019'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role ProtocolParameter.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role ProtocolParameter.container
  currentMap = {}
  contentMap['container'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-20-14:35:13_00001'] = currentMap
  loadMaps['WMSP.ProtocolParameter.container'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.container'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-20-14:35:13_00001'
  currentMap['name'] = 'container'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role ProtocolParameter.content
  currentMap = {}
  contentMap['content'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-20-14:35:13_00002'] = currentMap
  loadMaps['WMSP.ProtocolParameter.content'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.content'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-20-14:35:13_00002'
  currentMap['name'] = 'content'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False

  # Role ProtocolParameter.interfaceParameters
  currentMap = {}
  contentMap['interfaceParameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00031'] = currentMap
  loadMaps['WMSP.ProtocolParameter.interfaceParameters'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolParameter.interfaceParameters'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00031'
  currentMap['name'] = 'interfaceParameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of ProtocolParameter

  currentMap = abstractTypes.get('ProtocolParameter')
  aList = ['code', 'hicard', 'ioRole', 'locard', 'paramType', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['defaultStrings', 'name', 'content', 'interfaceParameters']
  currentMap['simpleAttrs'] = aList
  aList = ['container']
  currentMap['optLinks'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class ProtocolService
  currentMap = {}
  abstractTypes['ProtocolService'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00004'] = currentMap
  loadMaps['WMSP.ProtocolService'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00004'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'protocolServices'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolService
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ProtocolService.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ProtocolService.login
  currentMap = {}
  contentMap['login'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00014'] = currentMap
  loadMaps['WMSP.ProtocolService.login'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService.login'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00014'
  currentMap['name'] = 'login'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ProtocolService.result
  currentMap = {}
  contentMap['result'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00017'] = currentMap
  loadMaps['WMSP.ProtocolService.result'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService.result'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00017'
  currentMap['name'] = 'result'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute ProtocolService.run
  currentMap = {}
  contentMap['run'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00015'] = currentMap
  loadMaps['WMSP.ProtocolService.run'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService.run'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00015'
  currentMap['name'] = 'run'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ProtocolService.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00012'] = currentMap
  loadMaps['WMSP.ProtocolService.serial'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00012'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute ProtocolService.status
  currentMap = {}
  contentMap['status'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00016'] = currentMap
  loadMaps['WMSP.ProtocolService.status'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService.status'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00016'
  currentMap['name'] = 'status'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute ProtocolService.url
  currentMap = {}
  contentMap['url'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00013'] = currentMap
  loadMaps['WMSP.ProtocolService.url'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService.url'
  currentMap['type'] = 'dobj'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00013'
  currentMap['name'] = 'url'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('IMPL').get('abstractTypes')

  # Role ProtocolService.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role ProtocolService.protocolAccesss
  currentMap = {}
  contentMap['protocolAccesss'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00011'] = currentMap
  loadMaps['WMSP.ProtocolService.protocolAccesss'] = currentMap
  currentMap['tag'] = 'WMSP.ProtocolService.protocolAccesss'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-13:30:17_00011'
  currentMap['name'] = 'protocolAccesss'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('WMSP').get('abstractTypes')
  # End of ProtocolService

  currentMap = abstractTypes.get('ProtocolService')
  aList = ['serial']
  currentMap['headerAttrs'] = aList
  aList = ['login', 'result', 'run', 'status']
  currentMap['simpleAttrs'] = aList
  aList = ['protocolAccesss', 'access', 'url', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['protocolAccesss']
  currentMap['children'] = aList

  # Class WmsProtocol
  currentMap = {}
  abstractTypes['WmsProtocol'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00002'] = currentMap
  loadMaps['WMSP.WmsProtocol'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00002'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'wmsProtocols'
  currentMap['isTop'] = True
  currentMap['objkey'] = 'name'
  currentMap['class'] = cambridge.api.WmsProtocol.WmsProtocol
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute WmsProtocol.annealProtocolCode
  currentMap = {}
  contentMap['annealProtocolCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-08-05-11:53:29_00005'] = currentMap
  loadMaps['WMSP.WmsProtocol.annealProtocolCode'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.annealProtocolCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-08-05-11:53:29_00005'
  currentMap['name'] = 'annealProtocolCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute WmsProtocol.annealProtocolStoreName
  currentMap = {}
  contentMap['annealProtocolStoreName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-08-05-11:53:29_00004'] = currentMap
  loadMaps['WMSP.WmsProtocol.annealProtocolStoreName'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.annealProtocolStoreName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-08-05-11:53:29_00004'
  currentMap['name'] = 'annealProtocolStoreName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute WmsProtocol.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute WmsProtocol.createdBy
  contentMap['createdBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00002__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute WmsProtocol.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00015'] = currentMap
  loadMaps['WMSP.WmsProtocol.details'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00015'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute WmsProtocol.guid
  contentMap['guid'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:26_00002')

  # Attribute WmsProtocol.isModifiable
  contentMap['isModifiable'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-17-14:16:26_00010__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute WmsProtocol.lastUnlockedBy
  contentMap['lastUnlockedBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00003__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute WmsProtocol.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00014'] = currentMap
  loadMaps['WMSP.WmsProtocol.name'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00014'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute WmsProtocol.softwareName
  currentMap = {}
  contentMap['softwareName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00038'] = currentMap
  loadMaps['WMSP.WmsProtocol.softwareName'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.softwareName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00038'
  currentMap['name'] = 'softwareName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute WmsProtocol.softwareVersion
  currentMap = {}
  contentMap['softwareVersion'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00039'] = currentMap
  loadMaps['WMSP.WmsProtocol.softwareVersion'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.softwareVersion'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00039'
  currentMap['name'] = 'softwareVersion'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role WmsProtocol.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role WmsProtocol.annealProtocol
  currentMap = {}
  contentMap['annealProtocol'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-08-05-11:53:29_00003'] = currentMap
  loadMaps['WMSP.WmsProtocol.annealProtocol'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.annealProtocol'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-08-05-11:53:29_00003'
  currentMap['name'] = 'annealProtocol'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('ANPR').get('exolinks')

  # Role WmsProtocol.protocolInterfaces
  currentMap = {}
  contentMap['protocolInterfaces'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00036'] = currentMap
  loadMaps['WMSP.WmsProtocol.protocolInterfaces'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.protocolInterfaces'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00036'
  currentMap['name'] = 'protocolInterfaces'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('WMSP').get('abstractTypes')

  # Role WmsProtocol.protocolParameters
  currentMap = {}
  contentMap['protocolParameters'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00011'] = currentMap
  loadMaps['WMSP.WmsProtocol.protocolParameters'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.protocolParameters'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00011'
  currentMap['name'] = 'protocolParameters'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('WMSP').get('abstractTypes')

  # Role WmsProtocol.protocolServices
  currentMap = {}
  contentMap['protocolServices'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00013'] = currentMap
  loadMaps['WMSP.WmsProtocol.protocolServices'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.protocolServices'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:57_00013'
  currentMap['name'] = 'protocolServices'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('WMSP').get('abstractTypes')

  # Role WmsProtocol.software
  currentMap = {}
  contentMap['software'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00037'] = currentMap
  loadMaps['WMSP.WmsProtocol.software'] = currentMap
  currentMap['tag'] = 'WMSP.WmsProtocol.software'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00037'
  currentMap['name'] = 'software'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('METH').get('exolinks')
  # End of WmsProtocol

  currentMap = abstractTypes.get('WmsProtocol')
  aList = ['createdBy', 'guid', 'isModifiable', 'lastUnlockedBy', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['annealProtocolCode', 'annealProtocolStoreName', 'details', 'softwareName', 'softwareVersion']
  currentMap['simpleAttrs'] = aList
  aList = ['protocolServices', 'protocolParameters', 'protocolInterfaces', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['protocolInterfaces', 'protocolParameters', 'protocolServices']
  currentMap['children'] = aList

  # Class InterfaceParameter
  currentMap = {}
  abstractTypes['InterfaceParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00002'] = currentMap
  loadMaps['WMSP.InterfaceParameter'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00002'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'interfaceParameters'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = cambridge.api.WmsProtocol.InterfaceParameter
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute InterfaceParameter.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute InterfaceParameter.col
  contentMap['col'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00012')

  # Attribute InterfaceParameter.colspan
  contentMap['colspan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00014')

  # Attribute InterfaceParameter.defaultStrings
  currentMap = {}
  contentMap['defaultStrings'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-10-14-11:18:11_00001'] = currentMap
  loadMaps['WMSP.InterfaceParameter.defaultStrings'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.defaultStrings'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-14-11:18:11_00001'
  currentMap['name'] = 'defaultStrings'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute InterfaceParameter.hicard
  currentMap = {}
  contentMap['hicard'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00005'] = currentMap
  loadMaps['WMSP.InterfaceParameter.hicard'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.hicard'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00005'
  currentMap['name'] = 'hicard'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['proc'] = 'direct'
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute InterfaceParameter.interfaceGroup
  contentMap['interfaceGroup'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00003')

  # Attribute InterfaceParameter.isEditable
  currentMap = {}
  contentMap['isEditable'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-05-23-10:59:43_00001'] = currentMap
  loadMaps['WMSP.InterfaceParameter.isEditable'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.isEditable'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-05-23-10:59:43_00001'
  currentMap['name'] = 'isEditable'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = True
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute InterfaceParameter.isOrdered
  currentMap = {}
  contentMap['isOrdered'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00010'] = currentMap
  loadMaps['WMSP.InterfaceParameter.isOrdered'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.isOrdered'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00010'
  currentMap['name'] = 'isOrdered'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute InterfaceParameter.locard
  currentMap = {}
  contentMap['locard'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00006'] = currentMap
  loadMaps['WMSP.InterfaceParameter.locard'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.locard'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00006'
  currentMap['name'] = 'locard'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00011')

  # Attribute InterfaceParameter.row
  contentMap['row'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00011')

  # Attribute InterfaceParameter.rowspan
  contentMap['rowspan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00013')

  # Attribute InterfaceParameter.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00003'] = currentMap
  loadMaps['WMSP.InterfaceParameter.serial'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00003'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role InterfaceParameter.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role InterfaceParameter.enumValues
  currentMap = {}
  contentMap['enumValues'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-05-26-12:12:14_00003'] = currentMap
  loadMaps['WMSP.InterfaceParameter.enumValues'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.enumValues'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-05-26-12:12:14_00003'
  currentMap['name'] = 'enumValues'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('WMSP').get('abstractTypes')

  # Role InterfaceParameter.protocolParameter
  currentMap = {}
  contentMap['protocolParameter'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00030'] = currentMap
  loadMaps['WMSP.InterfaceParameter.protocolParameter'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceParameter.protocolParameter'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00030'
  currentMap['name'] = 'protocolParameter'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['copyOverride'] = True
  # End of InterfaceParameter

  currentMap = abstractTypes.get('InterfaceParameter')
  aList = ['col', 'colspan', 'hicard', 'isEditable', 'isOrdered', 'locard', 'row', 'rowspan', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['defaultStrings', 'interfaceGroup']
  currentMap['simpleAttrs'] = aList
  aList = ['protocolParameter']
  currentMap['optLinks'] = aList
  aList = ['enumValues', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['enumValues']
  currentMap['children'] = aList

  # Class InterfaceLabel
  currentMap = {}
  abstractTypes['InterfaceLabel'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-10-11-16:36:18_00002'] = currentMap
  loadMaps['WMSP.InterfaceLabel'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceLabel'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-11-16:36:18_00002'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'interfaceLabels'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = cambridge.api.WmsProtocol.InterfaceLabel
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute InterfaceLabel.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute InterfaceLabel.col
  contentMap['col'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00012')

  # Attribute InterfaceLabel.colspan
  contentMap['colspan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00014')

  # Attribute InterfaceLabel.interfaceGroup
  contentMap['interfaceGroup'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00003')

  # Attribute InterfaceLabel.label
  currentMap = {}
  contentMap['label'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00002'] = currentMap
  loadMaps['WMSP.InterfaceLabel.label'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceLabel.label'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00002'
  currentMap['name'] = 'label'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute InterfaceLabel.row
  contentMap['row'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00011')

  # Attribute InterfaceLabel.rowspan
  contentMap['rowspan'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2011-03-22-17:23:24_00013')

  # Attribute InterfaceLabel.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00001'] = currentMap
  loadMaps['WMSP.InterfaceLabel.serial'] = currentMap
  currentMap['tag'] = 'WMSP.InterfaceLabel.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-11-16:36:20_00001'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role InterfaceLabel.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of InterfaceLabel

  currentMap = abstractTypes.get('InterfaceLabel')
  aList = ['col', 'colspan', 'row', 'rowspan', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['interfaceGroup', 'label']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Out-of-package link to EnumValue
  currentMap = {}
  exolinks['EnumValue'] = currentMap
  loadMaps['WMSP.exo-EnumValue'] = currentMap
  currentMap['tag'] = 'WMSP.exo-EnumValue'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00003'
  currentMap['name'] = 'EnumValue'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.EnumValue
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to ProtocolAccess
  currentMap = {}
  exolinks['ProtocolAccess'] = currentMap
  loadMaps['WMSP.exo-ProtocolAccess'] = currentMap
  currentMap['tag'] = 'WMSP.exo-ProtocolAccess'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00005'
  currentMap['name'] = 'ProtocolAccess'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolAccess
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to ProtocolInterface
  currentMap = {}
  exolinks['ProtocolInterface'] = currentMap
  loadMaps['WMSP.exo-ProtocolInterface'] = currentMap
  currentMap['tag'] = 'WMSP.exo-ProtocolInterface'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00001'
  currentMap['name'] = 'ProtocolInterface'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolInterface
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))

  # Out-of-package link to ProtocolParameter
  currentMap = {}
  exolinks['ProtocolParameter'] = currentMap
  loadMaps['WMSP.exo-ProtocolParameter'] = currentMap
  currentMap['tag'] = 'WMSP.exo-ProtocolParameter'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00003'
  currentMap['name'] = 'ProtocolParameter'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolParameter
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to ProtocolService
  currentMap = {}
  exolinks['ProtocolService'] = currentMap
  loadMaps['WMSP.exo-ProtocolService'] = currentMap
  currentMap['tag'] = 'WMSP.exo-ProtocolService'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00004'
  currentMap['name'] = 'ProtocolService'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.ProtocolService
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to WmsProtocol
  currentMap = {}
  exolinks['WmsProtocol'] = currentMap
  loadMaps['WMSP.exo-WmsProtocol'] = currentMap
  currentMap['tag'] = 'WMSP.exo-WmsProtocol'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2010-05-06-12:26:54_00002'
  currentMap['name'] = 'WmsProtocol'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.WmsProtocol
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))

  # Out-of-package link to InterfaceParameter
  currentMap = {}
  exolinks['InterfaceParameter'] = currentMap
  loadMaps['WMSP.exo-InterfaceParameter'] = currentMap
  currentMap['tag'] = 'WMSP.exo-InterfaceParameter'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-03-22-17:23:22_00002'
  currentMap['name'] = 'InterfaceParameter'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.InterfaceParameter
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to InterfaceLabel
  currentMap = {}
  exolinks['InterfaceLabel'] = currentMap
  loadMaps['WMSP.exo-InterfaceLabel'] = currentMap
  currentMap['tag'] = 'WMSP.exo-InterfaceLabel'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2011-10-11-16:36:18_00002'
  currentMap['name'] = 'InterfaceLabel'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = cambridge.api.WmsProtocol.InterfaceLabel
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
